# Generated by Django 5.1.6 on 2025-02-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(default='รายละเอียดสินค้า'),
        ),
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.IntegerField(default='0001'),
        ),
    ]
