# Generated by Django 5.1.6 on 2025-02-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_detail_product_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อ')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='อีเมล')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='หัวข้อ')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
            ],
        ),
    ]
