# Generated by Django 5.1.6 on 2025-02-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_askqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
    ]
