# Generated by Django 5.1.6 on 2025-02-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_tracking_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='askqa',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='ตอบคำถาม'),
        ),
    ]
