# Generated by Django 5.1.6 on 2025-02-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_productname_price_productname_nomal_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productname',
            old_name='nomal_price',
            new_name='normal_price',
        ),
    ]
