# Generated by Django 5.1.6 on 2025-02-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_nomal_price_productname_normal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
