# Generated by Django 5.1.6 on 2025-02-27 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_machine_comments_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default='bank@mail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='Bank', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='myapp.comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='website',
            field=models.CharField(default='www.google.com', max_length=50),
            preserve_default=False,
        ),
    ]
