# Generated by Django 5.1.6 on 2025-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_machine_price_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slip',
            field=models.ImageField(blank=True, null=True, upload_to='machine-slip/'),
        ),
    ]
