# Generated by Django 5.1.6 on 2025-03-06 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('images', models.ImageField(upload_to='category-images/')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('qr_code', models.ImageField(upload_to='qr-codes/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('price_discount', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('images', models.ImageField(upload_to='menu-images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_buyer_price', models.FloatField(default=0)),
                ('count', models.IntegerField(default=1)),
                ('vat', models.FloatField(default=0)),
                ('final_price_with_vat', models.FloatField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendind', 'รอดำเนินการ'), ('in_process', 'อยู่ระหว่างดพเนินการ'), ('completed', 'เสร็จเรียบร้อย')], max_length=20)),
                ('menu', models.ManyToManyField(to='pos.menu')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.table')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item_total', models.FloatField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.menu')),
                ('order_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.ordermenu')),
            ],
        ),
    ]
