# Generated by Django 5.1.6 on 2025-03-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr-codes/'),
        ),
    ]
