# Generated by Django 5.1.6 on 2025-03-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_table_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='unit',
            field=models.CharField(default='แก้ว', max_length=20),
        ),
    ]
